### ISSUE TITLE
Identity Hub - Implement Verifiable Credential model

### ISSUE THREAD

**Issue by ouphi** [agera-edc/IdentityHub#12]
Feature #13

# Description
For now, we have a really simple implementation of the VerifiableCredential. This story is about implementing the VerifiableCredential model according to the [ following specs](https://www.w3.org/TR/vc-data-model/).

# Acceptance criteria
- [ ] VerifiableCredential respects the [following specs](https://www.w3.org/TR/vc-data-model/)

# Tasks
- [ ] Implement VerifiableCredential model
- [ ] Adapt validation according to the model and specs (dataFormat=application/vc+ldp)
- [ ] Adapt tests

**Comment by ouphi** [comment]
We agreed to use a minimalistic model only containing credentialsSubject, as they don't want to use the verifiable-credentials-java library.
