### ISSUE TITLE
Identity Hub - Handle Base64Url decoding/encoding of the data field

### ISSUE THREAD

**Issue by ouphi** [agera-edc/IdentityHub#14]
Feature #13

# Description
Make sure that the data field in MessageRequestObject is base64URL encoded and decoded.
Jackson automatically base64 encode/decode, but base64URL should be verified.

# Acceptance criteria
- [ ] The data field in MessageRequestObject is base64URL encoded and decoded

# Tasks
- [ ] Check if the byte[] are already automatically base64URL encoded or not
- [ ] If it is not the case, add the decoding and decoding.

**Comment by zeier** [comment]
Assigning to @ouphi to add description, acceptance criteria and tasks.

**Comment by ouphi** [comment]
Closing this story because the data field is a JWT and already base64Url encoded.
