### ISSUE TITLE
Identity Hub - Implementation and Integration Tests

### ISSUE THREAD

**Issue by marcgs** [agera-edc/IdentityHub#17]
Feature #13

## Description

Initial Identity Hub implementation supporting the following DWN interfaces in the [IdentityHubClient implementation](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/extensions/iam/decentralized-identity/identity-did-core/src/main/java/org/eclipse/dataspaceconnector/iam/did/hub/IdentityHubClientImpl.java):

- [Collections Query](https://identity.foundation/decentralized-web-node/spec/#query) to query Verifiable Credentials
- [Collections Write](https://identity.foundation/decentralized-web-node/spec/#write) to push Verifiable Credentials
- [Feature Detection](https://identity.foundation/decentralized-web-node/spec/#feature-detection) listing all the aforementioned operations as supported.

Messages need to be processed by a pipeline following [the tech specificacion](https://github.com/Metaform/mvd/blob/main/identity-hub/identity-hub-tech-spec.md#request-processing):
- The RequestProcessingService will dispatch to an InterfaceMethodProcessor based on interface type ("CollectionsWrite", "CollectionsQuery", "FeatureDetection") of the incoming method field of of each message in the request (requests contain an array of message objects).

The Identity Hub needs to be implemented as an EDC extension to support the [collocated test deployment topology](https://github.com/Metaform/mvd/blob/main/identity-hub/identity-hub-tech-spec.md#ii-deployment-topologies)

An HTTP client similar to [IdentityHubClient](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/extensions/iam/decentralized-identity/identity-did-core/src/main/java/org/eclipse/dataspaceconnector/iam/did/hub/IdentityHubClientImpl.java) must be provided in an own extension as well for easier client integration.

Verifiable Credentials follow the model in [the spec](https://www.w3.org/TR/vc-data-model/).

No Authentication/Authorisation required for any endpoint.

## Acceptance Criteria
- [x] Identity Hub is implemented as an EDC extension
- [x] Identity Hub supports the three operations listed above
- [x] Verifiable Credentials are implemented following the model in [the spec](https://www.w3.org/TR/vc-data-model/)
- [x] Identity Hub architecture according to the specs listed above
- [ ] ~Identity Hub client is implemented~ Moved to story agera-edc/MinimumViableDataspaceFork#5
- [ ] ~A CredentialsVerifier is implemented in similar way as [here](https://github.com/microsoft/edc-showcase/blob/main/extensions/identity-hub-verifier/src/main/java/org/eclipse/dataspaceconnector/iam/did/credentials/IdentityHubCredentialsVerifier.java) to retrieve Verifiable Credentials in the [DecentralizedIdentityService](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/extensions/iam/decentralized-identity/identity-did-service/src/main/java/org/eclipse/dataspaceconnector/identity/DecentralizedIdentityService.java#L94)~ Moved to story agera-edc/MinimumViableDataspaceFork#5 
- [x] Identity Hub is covered by Integration Tests checking that Verifiable Credentials can be pushed and queried back

## Tasks
- [x] Create module extension for Identity Hub REST API
  - [x] Implement Feature Detection endpoint
  - [x] Implement DWN and Verifiable Credentials model with serialization/deserialization
  - [x] Implement IdentityHubInMemoryStore
  - [x] Implement Collections Write endpoint
  - [x] Implement Collections Query endpoint
- [ ] ~Create module for Identity Hub client~
  - [ ] ~Implement IdentityHub HTTP client  (consider generating the client from an Open API spec)~
 - [ ] ~Create module for Identity Hub credentials verifier~
  - [ ] ~Implement `IdentityHubCredentialsVerifierImpl`~
- [ ] ~Create module for integration tests~
  - [ ] ~Implement Integration Tests writing Verifiable Credentials using the HTTP client and reading them with the `IdentityHubCredentialsVerifierImpl`~

**Comment by ouphi** [comment]
Scaffolding: 
- Add feature endpoint first - return empty list
- Add client + opanapi
- CD
- Do not use docker for the tests, use integration tests with EdcRuntimeExtension from "junit-extension" artifact
