### ISSUE TITLE
Identity Hub - In-Memory Store

### ISSUE THREAD

**Issue by ouphi** [agera-edc/IdentityHub#18]
Feature #13

# Description
We have a really simple implementation of the Identity Hub in-memory store.
This story is about improving the current implementation.

## Acceptance criteria
- [x] The store is thread safe
- [x] The store have a proper implementation and tests
- [x] The in-memory store if the default IdentityHubStore implementation (default extension)

## Tasks
- [x] Make the store thread safe
- [x] Add proper implementation and proper tests
- [x] Make the IdentityHubInMemoryExtension the default extension with the @Provider(isDefault = true) annotation.
