### ISSUE TITLE
IdentityHub - DWN spec correctness

### ISSUE THREAD

**Issue by ouphi** [agera-edc/IdentityHub#19]
Feature agera-edc/IdentityHub#13

# Description

Certain aspects of the [DWN spec](https://identity.foundation/decentralized-web-node/spec/) are not yet implemented:
- `messageId` property in `MessageResponseObject` must be a stringified Version 1 CID of the associated message
- `datCid` property in `Descriptor` should contain stringified Version 1 CID of the DAG PB encoded data
- `target` property in `RequestObject` must be the Decentralized Identifier base URI of the DID-relative URL

We added TODOs in the IdentityHub repository to remind us to implement these specs accordingly.
For each TODO, we should determine if the spec should be implemented and implement it if needed.

# Acceptance criteria
- [ ] Decision is taken which attributes are implemented according to spec, and which ones are left out
- [ ] Document decision taken 
- [ ] Validation rules for mandatory fields according to spec

# Tasks
- [ ] Documentation of spec coverage in current implementation
- [ ] Implement and validate missing properties according to spec
- [ ] Add tests for the validation

**Comment by zeier** [comment]
Won't implement for now, since Decentralized Web Node is a DRAFT specification under development. This should be implemented at a later stage once the DWN spec is stable.
