### ISSUE TITLE
Identity Hub - MVD integration

### ISSUE THREAD

**Issue by marcgs** [agera-edc/IdentityHub#21]
Feature #13

After #20 #32

## Description

Identity Hub needs to be integrated into the MVD to store and query Verifiable Credentials.

## Acceptance Criteria
- [x] Identity Hub EDC extension is included in MVD
- [x] Identity Hub write endpoint is used for seeding "region" Verifiable Credential ("eu" for connector 1 and 2, "us" for connector 3)
- [x] "Region" Verifiable Credential is used to filter out catalog accordingly
- [x] Local setup working with IdentityHub

## Tasks
- [x] Add Identity Hub extension to MVD
- [x] ~Extend Postman collection with request to load Verifiable Credential (region=XX) for each connector~ Use Identity Hub CLI to load region credential during deployment
- [x] Switch from CredentialsVerifierMock to IdentityHubCredentialsVerifier
- [ ] Verify that Verifiable Credentials are used properly in MVD
- [x] Local setup working with IdentityHub

**Comment by marcgs** [comment]
Seeding of region VC is easier using a CLI than using a Postman collection due to the complexity of the Identity Hub API. Suggesting to use a basic CLI already in this story.
