### ISSUE TITLE
Identity Hub - Remove Code from EDC Repo

### ISSUE THREAD

**Issue by marcgs** [agera-edc/IdentityHub#22]
Feature #13
Upstream https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/1373
After #21

## Description

IdentityHub embedded in EDC codebase can be removed once a standalone repository is ready.

## Acceptance Criteria
- [ ] IdentityHub code is removed from EDC Core
- [ ] Removal is communicated to the EDC community in alignment with Jim/Paul

## Tasks
- [ ] Remove code from EDC Core
- [ ] Communication to EDC community
