### ISSUE TITLE
IdentityHub - Get claims to apply policies ADR

### ISSUE THREAD

**Issue by ouphi** [agera-edc/IdentityHub#23]
Feature #13

# Description
ADR to define the workflow for getting a participant claims. These claims will be used to apply access policies.

There is an [EDC issue](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/1570) to discuss the CredentialVerifier contract.

# Acceptance criteria
- [x] Document the design
- [x] CredentialVerifier contract is defined (see [EDC issue](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/1570))

# Task
- [x] Write ADR
- [x] Agree about the CredentialVerifier contract with Jim & Paul
