### ISSUE TITLE
IdentityHub - Get and verify credentials

### ISSUE THREAD

**Issue by ouphi** [agera-edc/IdentityHub#24]
Feature #13

## Description
During IDS communication between 2 participants, before applying access policy, a participant needs to:
- Get the other participant's verifiableCredentials from IdentityHub
- Verify the signature of each verifiableCredential
- Extract the claims of a participant.

This story is about implementing this logic.

A [CredentialVerifier](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/extensions/iam/decentralized-identity/identity-did-spi/src/main/java/org/eclipse/dataspaceconnector/iam/did/spi/credentials/CredentialsVerifier.java) contract is defined in EDC.

The contract of the CredentialVerifier needs to be changed according to the [ADR](https://github.com/agera-edc/IdentityHub/pull/10).

Some resource:
Here is an example of a CredentialVerifier [here](https://github.com/microsoft/edc-showcase/blob/main/extensions/identity-hub-verifier/src/main/java/org/eclipse/dataspaceconnector/iam/did/credentials/IdentityHubCredentialsVerifier.java) retrieving Verifiable Credentials in the [DecentralizedIdentityService](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/blob/main/extensions/iam/decentralized-identity/identity-did-service/src/main/java/org/eclipse/dataspaceconnector/identity/DecentralizedIdentityService.java#L94). This is a quick implementation done before.

## Acceptance criteria
- [x] Logic to verifyCredentials is implemented
- [x] Logic to extract the claims is implemented
- [x] CredentialVerifier is adapted to the new contract

## Tasks
- [ ] Implement custom CredentialVerifier
- [x] Update CredentialVerifier contract in EDC
- [x] Adapt ITs
