### ISSUE TITLE
IdentityHub - Command line client 

### ISSUE THREAD

**Issue by Izzzu** [agera-edc/IdentityHub#25]
Feature #13

After #20 #21 agera-edc/MinimumViableDataspace#151

## Description

A command line application needs to be created which can act as Identity Hub client and this application is responsible for populating the Verifiable Credentials into participant's Identity Hub. This command line application internally uses IdentityHub API. A participant can be onboarded without the need of deploying it first.

MVD deployment pipeline should use this command line client in order to populate the Verifiable Credentials .

## Acceptance Criteria

- [x] CLI is documented
- [x] Identity Hub CLI can write VCs into an identityHub.
- [x] Testing coverage.

## Tasks

- [x] Implement Identity Hub CLI
- [x] Update docs and including local development instructions
- [ ] ~Use Identity Hub CLI in MVD deployment workflow to push VCs signed by GAIA-X Authority to participants Identity Hub during the onboarding~ (will be done in https://github.com/agera-edc/MinimumViableDataspace/issues/17)

**Comment by marcgs** [comment]
Initial CLI will be already created in #21 to populate VCs into the Identity Hub
